2023-05-01 02:50:58,397 INFO werkzeug MainThread :  * Running on http://127.0.0.1:8000/ (Press CTRL+C to quit)
2023-05-01 02:50:58,398 INFO werkzeug MainThread :  * Restarting with stat
2023-05-01 02:50:58,893 WARNING werkzeug MainThread :  * Debugger is active!
2023-05-01 02:50:58,894 INFO werkzeug MainThread :  * Debugger PIN: 968-689-477
2023-05-01 02:53:54,621 INFO app Thread-2 : returning all templates list from db
2023-05-01 02:53:54,621 INFO werkzeug Thread-2 : 127.0.0.1 - - [01/May/2023 02:53:54] "GET /templates HTTP/1.1" 200 -
2023-05-01 02:54:25,577 INFO werkzeug MainThread :  * Detected change in '/home/vishal/Documents/sem4/dfs/SVM/dfs_server/app.py', reloading
2023-05-01 02:54:26,086 INFO werkzeug MainThread :  * Restarting with stat
2023-05-01 02:54:26,629 WARNING werkzeug MainThread :  * Debugger is active!
2023-05-01 02:54:26,630 INFO werkzeug MainThread :  * Debugger PIN: 968-689-477
2023-05-01 02:54:31,399 INFO app Thread-2 : returning all templates list from db
2023-05-01 02:54:31,400 INFO werkzeug Thread-2 : 127.0.0.1 - - [01/May/2023 02:54:31] "GET /templates HTTP/1.1" 200 -
2023-05-01 02:55:03,894 INFO werkzeug MainThread :  * Detected change in '/home/vishal/Documents/sem4/dfs/SVM/dfs_server/app.py', reloading
2023-05-01 02:55:04,492 INFO werkzeug MainThread :  * Restarting with stat
2023-05-01 02:55:05,114 WARNING werkzeug MainThread :  * Debugger is active!
2023-05-01 02:55:05,115 INFO werkzeug MainThread :  * Debugger PIN: 968-689-477
2023-05-01 02:55:17,247 INFO app Thread-2 : returning all templates list from db
2023-05-01 02:55:17,250 INFO werkzeug Thread-2 : 127.0.0.1 - - [01/May/2023 02:55:17] "GET /templates HTTP/1.1" 200 -
2023-05-01 02:56:12,790 INFO werkzeug MainThread :  * Detected change in '/home/vishal/Documents/sem4/dfs/SVM/dfs_server/app.py', reloading
2023-05-01 02:56:13,318 INFO werkzeug MainThread :  * Restarting with stat
2023-05-01 02:56:13,864 WARNING werkzeug MainThread :  * Debugger is active!
2023-05-01 02:56:13,865 INFO werkzeug MainThread :  * Debugger PIN: 968-689-477
2023-05-01 02:56:16,161 INFO app Thread-2 : received request for get_templates()
2023-05-01 02:56:16,436 INFO app Thread-2 : returning all templates list from db
2023-05-01 02:56:16,438 INFO werkzeug Thread-2 : 127.0.0.1 - - [01/May/2023 02:56:16] "GET /templates HTTP/1.1" 200 -
2023-05-01 02:56:57,782 INFO werkzeug MainThread :  * Detected change in '/home/vishal/Documents/sem4/dfs/SVM/dfs_server/app.py', reloading
2023-05-01 02:56:58,240 INFO werkzeug MainThread :  * Restarting with stat
2023-05-01 02:56:58,752 WARNING werkzeug MainThread :  * Debugger is active!
2023-05-01 02:56:58,752 INFO werkzeug MainThread :  * Debugger PIN: 968-689-477
2023-05-01 02:57:09,181 INFO werkzeug MainThread :  * Detected change in '/home/vishal/Documents/sem4/dfs/SVM/dfs_server/app.py', reloading
2023-05-01 02:57:09,702 INFO werkzeug MainThread :  * Restarting with stat
2023-05-01 02:57:10,215 WARNING werkzeug MainThread :  * Debugger is active!
2023-05-01 02:57:10,215 INFO werkzeug MainThread :  * Debugger PIN: 968-689-477
2023-05-01 02:57:35,778 INFO app Thread-2 : received request for get_library_detail()
2023-05-01 02:57:36,241 INFO app Thread-2 : returning entries in db for os ubuntu
2023-05-01 02:57:36,243 INFO werkzeug Thread-2 : 127.0.0.1 - - [01/May/2023 02:57:36] "GET /library/os/ubuntu HTTP/1.1" 200 -
2023-05-01 02:58:40,089 INFO werkzeug MainThread :  * Detected change in '/home/vishal/Documents/sem4/dfs/SVM/dfs_server/app.py', reloading
2023-05-01 18:56:32,012 INFO werkzeug MainThread :  * Running on http://127.0.0.1:8000/ (Press CTRL+C to quit)
2023-05-01 18:56:32,013 INFO werkzeug MainThread :  * Restarting with stat
2023-05-01 18:56:32,545 WARNING werkzeug MainThread :  * Debugger is active!
2023-05-01 18:56:32,546 INFO werkzeug MainThread :  * Debugger PIN: 968-689-477
2023-05-01 18:56:43,903 INFO app Thread-2 : received request for get_library_detail()
2023-05-01 18:56:44,210 INFO app Thread-2 : returning entries in db for os alpine
2023-05-01 18:56:44,211 INFO werkzeug Thread-2 : 127.0.0.1 - - [01/May/2023 18:56:44] "GET /library/os/alpine HTTP/1.1" 200 -
2023-05-01 18:59:44,124 INFO werkzeug MainThread :  * Detected change in '/home/vishal/Documents/sem4/dfs/SVM/dfs_server/app.py', reloading
2023-05-01 18:59:44,635 INFO werkzeug MainThread :  * Restarting with stat
2023-05-01 19:03:42,627 INFO werkzeug MainThread :  * Running on http://127.0.0.1:8000/ (Press CTRL+C to quit)
2023-05-01 19:03:42,628 INFO werkzeug MainThread :  * Restarting with stat
2023-05-01 19:03:43,117 WARNING werkzeug MainThread :  * Debugger is active!
2023-05-01 19:03:43,117 INFO werkzeug MainThread :  * Debugger PIN: 968-689-477
2023-05-01 19:03:47,600 INFO app Thread-2 : received request for get_library_detail()
2023-05-01 19:03:47,607 INFO werkzeug Thread-2 : 127.0.0.1 - - [01/May/2023 19:03:47] "[35m[1mGET /library/os HTTP/1.1[0m" 500 -
2023-05-01 19:04:11,811 INFO werkzeug MainThread :  * Detected change in '/home/vishal/Documents/sem4/dfs/SVM/dfs_server/database_ops.py', reloading
2023-05-01 19:04:12,380 INFO werkzeug MainThread :  * Restarting with stat
2023-05-01 19:04:12,900 WARNING werkzeug MainThread :  * Debugger is active!
2023-05-01 19:04:12,900 INFO werkzeug MainThread :  * Debugger PIN: 968-689-477
2023-05-01 19:04:23,369 INFO werkzeug MainThread :  * Detected change in '/home/vishal/Documents/sem4/dfs/SVM/dfs_server/app.py', reloading
2023-05-01 19:04:23,851 INFO werkzeug MainThread :  * Restarting with stat
2023-05-01 19:04:24,346 WARNING werkzeug MainThread :  * Debugger is active!
2023-05-01 19:04:24,346 INFO werkzeug MainThread :  * Debugger PIN: 968-689-477
2023-05-01 19:04:29,828 INFO werkzeug MainThread :  * Running on http://127.0.0.1:8000/ (Press CTRL+C to quit)
2023-05-01 19:04:29,829 INFO werkzeug MainThread :  * Restarting with stat
2023-05-01 19:04:30,409 WARNING werkzeug MainThread :  * Debugger is active!
2023-05-01 19:04:30,410 INFO werkzeug MainThread :  * Debugger PIN: 968-689-477
2023-05-01 19:04:34,912 INFO app Thread-2 : received request for get_library_detail()
2023-05-01 19:04:35,205 INFO app Thread-2 : returning entries for all operating system present in library
2023-05-01 19:04:35,206 INFO werkzeug Thread-2 : 127.0.0.1 - - [01/May/2023 19:04:35] "GET /library/os HTTP/1.1" 200 -
2023-05-01 19:04:42,225 INFO werkzeug MainThread :  * Detected change in '/home/vishal/Documents/sem4/dfs/SVM/dfs_server/app.py', reloading
2023-05-01 19:04:42,685 INFO werkzeug MainThread :  * Restarting with stat
2023-05-01 19:04:43,272 WARNING werkzeug MainThread :  * Debugger is active!
2023-05-01 19:04:43,273 INFO werkzeug MainThread :  * Debugger PIN: 968-689-477
2023-05-01 19:20:34,131 INFO werkzeug MainThread :  * Running on http://127.0.0.1:8000/ (Press CTRL+C to quit)
2023-05-01 19:20:34,131 INFO werkzeug MainThread :  * Restarting with stat
2023-05-01 19:20:34,649 WARNING werkzeug MainThread :  * Debugger is active!
2023-05-01 19:20:34,650 INFO werkzeug MainThread :  * Debugger PIN: 968-689-477
2023-05-01 19:20:57,628 INFO werkzeug MainThread :  * Detected change in '/home/vishal/Documents/sem4/dfs/SVM/dfs_server/app.py', reloading
2023-05-01 19:20:57,960 INFO werkzeug MainThread :  * Restarting with stat
2023-05-01 19:20:58,512 WARNING werkzeug MainThread :  * Debugger is active!
2023-05-01 19:20:58,512 INFO werkzeug MainThread :  * Debugger PIN: 968-689-477
2023-05-01 19:21:09,240 INFO werkzeug MainThread :  * Detected change in '/home/vishal/Documents/sem4/dfs/SVM/dfs_server/app.py', reloading
2023-05-01 19:21:09,776 INFO werkzeug MainThread :  * Restarting with stat
2023-05-01 19:21:10,519 DEBUG urllib3.connectionpool MainThread : Starting new HTTPS connection (1): api.ipify.org:443
2023-05-01 19:21:11,758 DEBUG urllib3.connectionpool MainThread : https://api.ipify.org:443 "GET / HTTP/1.1" 200 14
2023-05-01 19:21:11,765 WARNING werkzeug MainThread :  * Debugger is active!
2023-05-01 19:21:11,765 INFO werkzeug MainThread :  * Debugger PIN: 968-689-477
2023-05-01 19:24:10,383 DEBUG urllib3.connectionpool Thread-3 : Starting new HTTPS connection (1): ifconfig.co:443
2023-05-01 19:24:10,383 DEBUG urllib3.connectionpool Thread-2 : Starting new HTTPS connection (1): icanhazip.com:443
2023-05-01 19:24:10,389 DEBUG urllib3.connectionpool Thread-4 : Starting new HTTPS connection (1): ipinfo.io:443
2023-05-01 19:24:10,392 DEBUG urllib3.connectionpool Thread-5 : Starting new HTTPS connection (1): checkip.amazonaws.com:443
2023-05-01 19:24:10,392 DEBUG urllib3.connectionpool Thread-1 : Starting new HTTPS connection (1): ipecho.net:443
2023-05-01 19:24:10,394 DEBUG urllib3.connectionpool Thread-6 : Starting new HTTPS connection (1): api.ipify.org:443
2023-05-01 19:24:10,557 DEBUG urllib3.connectionpool Thread-2 : https://icanhazip.com:443 "GET / HTTP/1.1" 200 15
2023-05-01 19:24:10,558 INFO root Thread-2 : Asked https://icanhazip.com for our IP -> 218.185.248.66
2023-05-01 19:24:10,762 DEBUG urllib3.connectionpool Thread-4 : https://ipinfo.io:443 "GET /ip HTTP/1.1" 200 14
2023-05-01 19:24:10,764 INFO root Thread-4 : Asked https://ipinfo.io/ip for our IP -> 218.185.248.66
2023-05-01 19:24:10,772 DEBUG urllib3.connectionpool Thread-1 : https://ipecho.net:443 "GET /plain HTTP/1.1" 200 14
2023-05-01 19:24:10,773 INFO root Thread-1 : Asked https://ipecho.net/plain for our IP -> 218.185.248.66
2023-05-01 19:24:10,923 DEBUG urllib3.connectionpool Thread-3 : https://ifconfig.co:443 "GET /ip HTTP/1.1" 200 15
2023-05-01 19:24:10,924 INFO root Thread-3 : Asked https://ifconfig.co/ip for our IP -> 218.185.248.66
2023-05-01 19:24:11,206 DEBUG urllib3.connectionpool Thread-5 : https://checkip.amazonaws.com:443 "GET / HTTP/1.1" 200 15
2023-05-01 19:24:11,208 INFO root Thread-5 : Asked https://checkip.amazonaws.com for our IP -> 218.185.248.66
2023-05-01 19:24:12,343 DEBUG urllib3.connectionpool Thread-6 : https://api.ipify.org:443 "GET / HTTP/1.1" 200 14
2023-05-01 19:24:12,344 INFO root Thread-6 : Asked https://api.ipify.org for our IP -> 218.185.248.66
2023-05-01 19:24:12,351 INFO werkzeug MainThread :  * Running on http://127.0.0.1:8000/ (Press CTRL+C to quit)
2023-05-01 19:24:12,352 INFO werkzeug MainThread :  * Restarting with stat
2023-05-01 19:24:14,938 DEBUG urllib3.connectionpool Thread-5 : Starting new HTTPS connection (1): ipecho.net:443
2023-05-01 19:24:14,942 DEBUG urllib3.connectionpool Thread-2 : Starting new HTTPS connection (1): icanhazip.com:443
2023-05-01 19:24:14,944 DEBUG urllib3.connectionpool Thread-1 : Starting new HTTPS connection (1): ipinfo.io:443
2023-05-01 19:24:14,951 DEBUG urllib3.connectionpool Thread-6 : Starting new HTTPS connection (1): api.ipify.org:443
2023-05-01 19:24:14,951 DEBUG urllib3.connectionpool Thread-4 : Starting new HTTPS connection (1): checkip.amazonaws.com:443
2023-05-01 19:24:14,953 DEBUG urllib3.connectionpool Thread-3 : Starting new HTTPS connection (1): ifconfig.co:443
2023-05-01 19:24:15,101 DEBUG urllib3.connectionpool Thread-2 : https://icanhazip.com:443 "GET / HTTP/1.1" 200 15
2023-05-01 19:24:15,103 INFO root Thread-2 : Asked https://icanhazip.com for our IP -> 218.185.248.66
2023-05-01 19:24:15,282 DEBUG urllib3.connectionpool Thread-5 : https://ipecho.net:443 "GET /plain HTTP/1.1" 200 14
2023-05-01 19:24:15,283 INFO root Thread-5 : Asked https://ipecho.net/plain for our IP -> 218.185.248.66
2023-05-01 19:24:15,285 DEBUG urllib3.connectionpool Thread-1 : https://ipinfo.io:443 "GET /ip HTTP/1.1" 200 14
2023-05-01 19:24:15,287 INFO root Thread-1 : Asked https://ipinfo.io/ip for our IP -> 218.185.248.66
2023-05-01 19:24:15,329 DEBUG urllib3.connectionpool Thread-3 : https://ifconfig.co:443 "GET /ip HTTP/1.1" 200 15
2023-05-01 19:24:15,331 INFO root Thread-3 : Asked https://ifconfig.co/ip for our IP -> 218.185.248.66
2023-05-01 19:24:15,686 DEBUG urllib3.connectionpool Thread-4 : https://checkip.amazonaws.com:443 "GET / HTTP/1.1" 200 15
2023-05-01 19:24:15,687 INFO root Thread-4 : Asked https://checkip.amazonaws.com for our IP -> 218.185.248.66
2023-05-01 19:24:16,254 WARNING werkzeug MainThread :  * Debugger is active!
2023-05-01 19:24:16,255 INFO werkzeug MainThread :  * Debugger PIN: 968-689-477
2023-05-01 19:53:59,985 INFO app MainThread : registering service dfs-server at ip 192.168.1.109
2023-05-01 19:54:29,128 INFO app MainThread : registering service dfs-server at ip 192.168.1.109
2023-05-01 19:54:29,129 INFO app MainThread : found free port at 8000
2023-05-01 19:55:02,975 INFO app MainThread : registering service dfs-server at ip 192.168.1.109
2023-05-01 19:55:02,975 INFO app MainThread : found free port at 8000
2023-05-01 19:56:03,644 INFO app MainThread : registering service dfs-server at ip 192.168.1.109
2023-05-01 19:56:03,645 INFO app MainThread : found free port at 8000
2023-05-01 19:56:04,127 INFO werkzeug MainThread :  * Running on http://192.168.1.109:8000/ (Press CTRL+C to quit)
2023-05-01 19:56:04,128 INFO werkzeug MainThread :  * Restarting with stat
2023-05-01 19:56:04,597 INFO app MainThread : registering service dfs-server at ip 192.168.1.109
2023-05-01 19:56:04,597 INFO app MainThread : found free port at 8001
2023-05-01 19:56:05,077 WARNING werkzeug MainThread :  * Debugger is active!
2023-05-01 19:56:05,077 INFO werkzeug MainThread :  * Debugger PIN: 968-689-477
2023-05-02 14:53:39,012 INFO app MainThread : registering service dfs-server at ip 192.168.1.109
2023-05-02 14:53:39,012 INFO app MainThread : found free port at 8000
2023-05-02 14:53:48,730 INFO werkzeug MainThread :  * Running on http://192.168.1.109:8000/ (Press CTRL+C to quit)
2023-05-02 14:53:48,731 INFO werkzeug MainThread :  * Restarting with stat
2023-05-02 14:53:49,235 INFO app MainThread : registering service dfs-server at ip 192.168.1.109
2023-05-02 14:53:49,235 INFO app MainThread : found free port at 8001
2023-05-02 14:53:56,984 WARNING werkzeug MainThread :  * Debugger is active!
2023-05-02 14:53:56,984 INFO werkzeug MainThread :  * Debugger PIN: 968-689-477
2023-05-02 14:57:33,957 INFO app MainThread : registering service dfs-server at ip 192.168.1.109
2023-05-02 14:57:33,957 INFO app MainThread : found free port at 8000
2023-05-02 14:57:44,242 INFO werkzeug MainThread :  * Running on http://192.168.1.109:8000/ (Press CTRL+C to quit)
2023-05-02 14:57:44,243 INFO werkzeug MainThread :  * Restarting with stat
2023-05-02 14:57:50,041 INFO app MainThread : registering service dfs-server at ip 192.168.1.109
2023-05-02 14:57:50,042 INFO app MainThread : found free port at 8001
2023-05-02 14:57:50,888 WARNING werkzeug MainThread :  * Debugger is active!
2023-05-02 14:57:50,888 INFO werkzeug MainThread :  * Debugger PIN: 968-689-477
2023-05-02 15:00:10,655 INFO werkzeug MainThread :  * Detected change in '/home/vishal/Documents/sem4/dfs/SVM/dfs_server/app.py', reloading
2023-05-02 15:00:11,178 INFO werkzeug MainThread :  * Restarting with stat
2023-05-02 15:00:16,103 INFO app MainThread : registering service dfs-server at ip 192.168.1.109
2023-05-02 15:00:16,103 INFO app MainThread : found free port at 8001
2023-05-02 15:00:29,920 INFO app MainThread : registering service dfs-server at ip 192.168.1.109
2023-05-02 15:00:29,920 INFO app MainThread : found free port at 8000
2023-05-02 15:00:30,731 INFO app MainThread : registering service dfs-server at ip 192.168.1.109 and port 8000
2023-05-02 15:00:30,736 INFO werkzeug MainThread :  * Running on http://192.168.1.109:8000/ (Press CTRL+C to quit)
2023-05-02 15:00:30,738 INFO werkzeug MainThread :  * Restarting with stat
2023-05-02 15:00:31,252 INFO app MainThread : registering service dfs-server at ip 192.168.1.109
2023-05-02 15:00:31,252 INFO app MainThread : found free port at 8001
2023-05-02 15:00:32,092 INFO app MainThread : registering service dfs-server at ip 192.168.1.109 and port 8001
2023-05-02 15:00:32,102 WARNING werkzeug MainThread :  * Debugger is active!
2023-05-02 15:00:32,103 INFO werkzeug MainThread :  * Debugger PIN: 968-689-477
2023-05-02 15:00:57,426 INFO app Thread-2 : received request for retireieve_all_configs()
2023-05-02 15:00:57,433 INFO werkzeug Thread-2 : 192.168.1.109 - - [02/May/2023 15:00:57] "[35m[1mGET /configs HTTP/1.1[0m" 500 -
2023-05-02 15:01:15,614 INFO werkzeug MainThread :  * Detected change in '/home/vishal/Documents/sem4/dfs/SVM/dfs_server/database_ops.py', reloading
2023-05-02 15:01:16,191 INFO werkzeug MainThread :  * Restarting with stat
2023-05-02 15:03:38,212 INFO app MainThread : registering service dfs-server at ip 192.168.1.109
2023-05-02 15:03:38,212 INFO app MainThread : found free port at 8000
2023-05-02 15:03:39,054 INFO app MainThread : registering service dfs-server at ip 192.168.1.109 and port 8000
2023-05-02 15:03:39,087 INFO werkzeug MainThread :  * Running on http://192.168.1.109:8000/ (Press CTRL+C to quit)
2023-05-02 15:03:58,510 INFO app Thread-1 : received request for retireieve_all_configs()
2023-05-02 15:03:58,720 INFO app Thread-1 : returning all configs list from db
2023-05-02 15:03:58,723 INFO werkzeug Thread-1 : 192.168.1.109 - - [02/May/2023 15:03:58] "GET /configs HTTP/1.1" 200 -
2023-05-02 15:58:14,575 INFO app MainThread : registering service dfs-server at ip 192.168.1.109
2023-05-02 15:58:14,575 INFO app MainThread : found free port at 8000
2023-05-02 15:58:15,160 INFO app MainThread : registering service dfs-server at ip 192.168.1.109 and port 8000
2023-05-02 15:58:15,171 INFO werkzeug MainThread :  * Running on http://192.168.1.109:8000/ (Press CTRL+C to quit)
2023-05-04 12:27:23,041 INFO app MainThread : registering service dfs-server at ip 10.1.37.194
2023-05-04 12:27:23,041 INFO app MainThread : found free port at 8000
2023-05-04 12:27:23,436 INFO app MainThread : registering service dfs-server at ip 10.1.37.194 and port 8000
2023-05-04 12:27:23,439 INFO werkzeug MainThread :  * Running on http://10.1.37.194:8000/ (Press CTRL+C to quit)
2023-05-04 13:04:47,129 INFO werkzeug Thread-1 : 10.1.37.194 - - [04/May/2023 13:04:47] "[35m[1mPOST /provision/644ecff1e88c3dfee88009a4 HTTP/1.1[0m" 500 -
2023-05-04 13:09:25,041 INFO app MainThread : registering service dfs-server at ip 10.1.37.194
2023-05-04 13:09:25,041 INFO app MainThread : found free port at 8000
2023-05-04 13:09:25,449 INFO app MainThread : registering service dfs-server at ip 10.1.37.194 and port 8000
2023-05-04 13:09:25,453 INFO werkzeug MainThread :  * Running on http://10.1.37.194:8000/ (Press CTRL+C to quit)
2023-05-04 13:09:29,223 ERROR app Thread-1 : Exception on /provision/644ecff1e88c3dfee88009a4 [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 182, in provision_env
    deployable_node = get_response(f'{node_manager_address}{app.config["NODE_MANAGER_NODE_INFO_API"]}', config_obj[0]['resources'])
  File "/home/vishal/Documents/sem4/dfs/SVM/dfs_server/helper.py", line 58, in get_response
    ans = requests.get(ip_address, params=data).content.decode()
  File "/home/vishal/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/vishal/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/vishal/.local/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/vishal/.local/lib/python3.8/site-packages/requests/sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/vishal/.local/lib/python3.8/site-packages/requests/sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '10.1.37.194:8003/node_info'
2023-05-04 13:09:29,238 INFO werkzeug Thread-1 : 10.1.37.194 - - [04/May/2023 13:09:29] "[35m[1mPOST /provision/644ecff1e88c3dfee88009a4 HTTP/1.1[0m" 500 -
2023-05-04 13:09:45,551 ERROR app Thread-2 : Exception on /provision/644ecff1e88c3dfee88009a4 [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 182, in provision_env
    deployable_node = get_response(f'{node_manager_address}{app.config["NODE_MANAGER_NODE_INFO_API"]}', config_obj[0]['resources'])
  File "/home/vishal/Documents/sem4/dfs/SVM/dfs_server/helper.py", line 58, in get_response
    ans = requests.get(ip_address, params=data).content.decode()
  File "/home/vishal/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/vishal/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/vishal/.local/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/vishal/.local/lib/python3.8/site-packages/requests/sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/vishal/.local/lib/python3.8/site-packages/requests/sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '10.1.37.194:8003/node_info'
2023-05-04 13:09:45,552 INFO werkzeug Thread-2 : 10.1.37.194 - - [04/May/2023 13:09:45] "[35m[1mPOST /provision/644ecff1e88c3dfee88009a4 HTTP/1.1[0m" 500 -
2023-05-04 13:12:43,294 INFO app MainThread : registering service dfs-server at ip 10.1.37.194
2023-05-04 13:12:43,294 INFO app MainThread : found free port at 8000
2023-05-04 13:12:43,718 INFO app MainThread : registering service dfs-server at ip 10.1.37.194 and port 8000
2023-05-04 13:12:43,724 INFO werkzeug MainThread :  * Running on http://10.1.37.194:8000/ (Press CTRL+C to quit)
2023-05-04 13:14:43,943 INFO app MainThread : registering service dfs-server at ip 10.1.37.194
2023-05-04 13:14:43,943 INFO app MainThread : found free port at 8000
2023-05-04 13:14:44,319 INFO app MainThread : registering service dfs-server at ip 10.1.37.194 and port 8000
2023-05-04 13:14:44,322 INFO werkzeug MainThread :  * Running on http://10.1.37.194:8000/ (Press CTRL+C to quit)
2023-05-04 13:16:40,566 DEBUG urllib3.connectionpool Thread-1 : Starting new HTTP connection (1): 10.1.37.194:8003
2023-05-04 13:16:40,569 DEBUG urllib3.connectionpool Thread-1 : http://10.1.37.194:8003 "GET /node_info?ram=1G&cpu=1.0&gpu=1&storage=54 HTTP/1.1" 500 290
2023-05-04 13:16:40,570 ERROR app Thread-1 : Exception on /provision/644ecff1e88c3dfee88009a4 [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 182, in provision_env
    deployable_node = get_response(f'{node_manager_address}{app.config["NODE_MANAGER_NODE_INFO_API"]}', config_obj[0]['resources'])
  File "/home/vishal/Documents/sem4/dfs/SVM/dfs_server/helper.py", line 59, in get_response
    ans = json.loads(ans)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-05-04 13:16:40,588 INFO werkzeug Thread-1 : 10.1.37.194 - - [04/May/2023 13:16:40] "[35m[1mPOST /provision/644ecff1e88c3dfee88009a4 HTTP/1.1[0m" 500 -
2023-05-04 13:17:55,743 DEBUG urllib3.connectionpool Thread-2 : Starting new HTTP connection (1): 10.1.37.194:8003
2023-05-04 13:17:55,746 DEBUG urllib3.connectionpool Thread-2 : http://10.1.37.194:8003 "GET /node_info?ram=1G&cpu=1.0&gpu=1&storage=54 HTTP/1.1" 500 290
2023-05-04 13:17:55,747 ERROR app Thread-2 : Exception on /provision/644ecff1e88c3dfee88009a4 [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 182, in provision_env
    deployable_node = get_response(f'{node_manager_address}{app.config["NODE_MANAGER_NODE_INFO_API"]}', config_obj[0]['resources'])
  File "/home/vishal/Documents/sem4/dfs/SVM/dfs_server/helper.py", line 59, in get_response
    ans = json.loads(ans)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-05-04 13:17:55,748 INFO werkzeug Thread-2 : 10.1.37.194 - - [04/May/2023 13:17:55] "[35m[1mPOST /provision/644ecff1e88c3dfee88009a4 HTTP/1.1[0m" 500 -
2023-05-04 13:18:47,909 DEBUG urllib3.connectionpool Thread-3 : Starting new HTTP connection (1): 10.1.37.194:8004
2023-05-04 13:18:47,913 DEBUG urllib3.connectionpool Thread-3 : http://10.1.37.194:8004 "GET /node_info?ram=1G&cpu=1.0&gpu=1&storage=54 HTTP/1.1" 500 290
2023-05-04 13:18:47,914 ERROR app Thread-3 : Exception on /provision/644ecff1e88c3dfee88009a4 [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 182, in provision_env
    deployable_node = get_response(f'{node_manager_address}{app.config["NODE_MANAGER_NODE_INFO_API"]}', config_obj[0]['resources'])
  File "/home/vishal/Documents/sem4/dfs/SVM/dfs_server/helper.py", line 59, in get_response
    ans = json.loads(ans)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-05-04 13:18:47,915 INFO werkzeug Thread-3 : 10.1.37.194 - - [04/May/2023 13:18:47] "[35m[1mPOST /provision/644ecff1e88c3dfee88009a4 HTTP/1.1[0m" 500 -
2023-05-04 13:21:46,650 DEBUG urllib3.connectionpool Thread-4 : Starting new HTTP connection (1): 10.1.37.194:8004
2023-05-04 13:21:46,653 DEBUG urllib3.connectionpool Thread-4 : http://10.1.37.194:8004 "GET /node_info?ram=1G&cpu=1.0&gpu=1&storage=54 HTTP/1.1" 500 290
2023-05-04 13:21:46,653 ERROR app Thread-4 : Exception on /provision/644ecff1e88c3dfee88009a4 [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 182, in provision_env
    deployable_node = post_response(f'{node_manager_address}{app.config["NODE_MANAGER_NODE_INFO_API"]}', config_obj[0]['resources'])
  File "/home/vishal/Documents/sem4/dfs/SVM/dfs_server/helper.py", line 59, in get_response
    ans = json.loads(ans)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-05-04 13:21:46,654 INFO werkzeug Thread-4 : 10.1.37.194 - - [04/May/2023 13:21:46] "[35m[1mPOST /provision/644ecff1e88c3dfee88009a4 HTTP/1.1[0m" 500 -
2023-05-04 13:22:07,249 INFO app MainThread : registering service dfs-server at ip 10.1.37.194
2023-05-04 13:22:07,249 INFO app MainThread : found free port at 8003
2023-05-04 13:22:07,669 INFO app MainThread : registering service dfs-server at ip 10.1.37.194 and port 8003
2023-05-04 13:22:07,673 INFO werkzeug MainThread :  * Running on http://10.1.37.194:8003/ (Press CTRL+C to quit)
2023-05-04 13:22:34,180 ERROR app Thread-1 : Exception on /provision/644ecff1e88c3dfee88009a4 [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 182, in provision_env
    deployable_node = post_response(f'{node_manager_address}{app.config["NODE_MANAGER_NODE_INFO_API"]}', config_obj[0]['resources'])
NameError: name 'post_response' is not defined
2023-05-04 13:22:34,183 INFO werkzeug Thread-1 : 10.1.37.194 - - [04/May/2023 13:22:34] "[35m[1mPOST /provision/644ecff1e88c3dfee88009a4 HTTP/1.1[0m" 500 -
2023-05-04 13:24:54,832 INFO app MainThread : registering service dfs-server at ip 10.1.37.194
2023-05-04 13:24:54,832 INFO app MainThread : found free port at 8000
2023-05-04 13:24:55,237 INFO app MainThread : registering service dfs-server at ip 10.1.37.194 and port 8000
2023-05-04 13:24:55,241 INFO werkzeug MainThread :  * Running on http://10.1.37.194:8000/ (Press CTRL+C to quit)
2023-05-04 13:25:06,330 DEBUG urllib3.connectionpool Thread-1 : Starting new HTTP connection (1): 10.1.37.194:8005
2023-05-04 13:25:06,335 DEBUG urllib3.connectionpool Thread-1 : http://10.1.37.194:8005 "POST /node_info HTTP/1.1" 500 290
2023-05-04 13:25:06,336 ERROR app Thread-1 : Exception on /provision/644ecff1e88c3dfee88009a4 [POST]
Traceback (most recent call last):
  File "/home/vishal/.local/lib/python3.8/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 182, in provision_env
    deployable_node = post_response(node_manager_address, app.config["NODE_MANAGER_NODE_INFO_API"], config_obj[0]['resources'])
  File "/home/vishal/Documents/sem4/dfs/SVM/dfs_server/helper.py", line 63, in post_response
    ans = requests.post(ip_address + function, json=data).json()
  File "/home/vishal/.local/lib/python3.8/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
: 0
2023-05-04 13:25:06,549 INFO werkzeug Thread-1 : 10.1.37.194 - - [04/May/2023 13:25:06] "[35m[1mPOST /provision/644ecff1e88c3dfee88009a4 HTTP/1.1[0m" 500 -
2023-05-04 13:26:50,876 INFO app MainThread : registering service dfs-server at ip 10.1.37.194
2023-05-04 13:26:50,877 INFO app MainThread : found free port at 8000
2023-05-04 13:26:51,239 INFO app MainThread : registering service dfs-server at ip 10.1.37.194 and port 8000
2023-05-04 13:26:51,242 INFO werkzeug MainThread :  * Running on http://10.1.37.194:8000/ (Press CTRL+C to quit)
2023-05-04 13:26:57,149 ERROR app Thread-1 : Exception on /provision/644ecff1e88c3dfee88009a4 [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 178, in provision_env
    deployable_node = post_response(node_manager_address, app.config["NODE_MANAGER_NODE_INFO_API"], config_obj)
  File "/home/vishal/Documents/sem4/dfs/SVM/dfs_server/helper.py", line 63, in post_response
    ans = requests.post(ip_address + function, json=data).json()
  File "/home/vishal/.local/lib/python3.8/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/vishal/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/vishal/.local/lib/python3.8/site-packages/requests/sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "/home/vishal/.local/lib/python3.8/site-packages/requests/sessions.py", line 443, in prepare_request
    p.prepare(
  File "/home/vishal/.local/lib/python3.8/site-packages/requests/models.py", line 321, in prepare
    self.prepare_body(data, files, json)
  File "/home/vishal/.local/lib/python3.8/site-packages/requests/models.py", line 473, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 385, in dumps
    return cls(
  File "/usr/lib/python3/dist-packages/simplejson/encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3/dist-packages/simplejson/encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3/dist-packages/simplejson/encoder.py", line 272, in default
    raise TypeError('Object of type %s is not JSON serializable' %
TypeError: Object of type ObjectId is not JSON serializable
2023-05-04 13:26:57,163 INFO werkzeug Thread-1 : 10.1.37.194 - - [04/May/2023 13:26:57] "[35m[1mPOST /provision/644ecff1e88c3dfee88009a4 HTTP/1.1[0m" 500 -
2023-05-04 13:35:04,309 INFO app MainThread : registering service dfs-server at ip 10.1.37.194
2023-05-04 13:35:04,310 INFO app MainThread : found free port at 8000
2023-05-04 13:35:04,810 INFO app MainThread : registering service dfs-server at ip 10.1.37.194 and port 8000
2023-05-04 13:35:04,813 INFO werkzeug MainThread :  * Running on http://10.1.37.194:8000/ (Press CTRL+C to quit)
2023-05-04 13:35:09,440 DEBUG urllib3.connectionpool Thread-1 : Starting new HTTP connection (1): 10.1.37.194:8005
2023-05-04 13:35:09,442 DEBUG urllib3.connectionpool Thread-1 : http://10.1.37.194:8005 "POST /node_info HTTP/1.1" 200 42
2023-05-04 13:35:09,443 ERROR app Thread-1 : failed to find enough free resources for config id 644ecff1e88c3dfee88009a4
2023-05-04 13:35:09,444 INFO werkzeug Thread-1 : 10.1.37.194 - - [04/May/2023 13:35:09] "[35m[1mPOST /provision/644ecff1e88c3dfee88009a4 HTTP/1.1[0m" 500 -
